Repository ProjectToStudy/sessac-e, pull requests merged in 2023-01, with the labels that each got.

#16 Front end
  client/public/images/arrow-back-24.svg
  client/public/images/search.svg
  client/src/App.tsx
  client/src/api/user.ts
  client/src/components/atoms/Header.tsx
  client/src/components/atoms/Navigation.tsx
  client/src/components/atoms/index.ts
  client/src/components/study/Study.tsx
  client/src/components/user/join/JoinPlanting.tsx
  client/src/containers/study/Study.tsx
  client/src/containers/user/Join.tsx
  client/src/containers/user/JoinPlanting.tsx
  client/src/index.css
  client/src/modules/user.ts
  client/src/pages/Home.tsx
  client/src/pages/index.ts
  client/src/pages/study/Study.tsx
  client/src/pages/user/JoinPlanting.tsx
  client/src/styles/Component.module.scss
  client/src/styles/Study.module.scss
  client/src/utils/cookie.ts
Labels: ✨ Feat, 🐱 chore

#19 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/api/routes/user.js
  server/src/app.js
  server/src/middleware/auth.js
Labels: 🛠 Fix

#20 Front end
  client/src/api/user.ts
  client/src/containers/user/Join.tsx
Labels: 🛠 Fix

#21 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/app.js
Labels: 🛠 Fix

#22 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/api/routes/user.js
  server/src/middleware/auth.js
Labels: 🛠 Fix

#23 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/api/routes/user.js
  server/src/middleware/auth.js
Labels: 🛠 Fix

#24 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/api/routes/user.js
  server/src/app.js
  server/src/middleware/auth.js
Labels: 🛠 Fix

#25 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/app.js
Labels: 🛠 Fix

#26 fix: 엑세스 토큰 쿠키에 넣는 로직 수정
  server/src/api/routes/user.js
  server/src/middleware/auth.js
Labels: 🛠 Fix

#27 Front end
  client/public/images/nav/home.svg
  client/public/images/nav/mypage-active.svg
  client/public/images/nav/mystudy-active.svg
  client/public/images/nav/studylist-active.svg
  client/src/api/user.ts
  client/src/containers/user/Join.tsx
  client/src/styles/Component.module.scss
  client/src/utils/cookie.ts
Labels: ✨ Feat
