Repository ProjectToStudy/sessac-e, pull requests merged in 2023-04, with the labels that each got.

#32 Backend
  server/src/api/routes/user.js
  server/src/controllers/team.js
  server/src/controllers/user.js
  server/src/middleware/errorHandler.js
  server/src/models/teamCategoryInfo.js
  server/src/models/teamStatsInfo.js
  server/src/services/team/index.js
  server/src/services/user/index.js
  server/src/utils/array.js
  server/src/utils/datetime.js
Labels: ✨ Feat, 🐻 refactor

#34 design: 스터디 찾기 페이지 UI 추가
  client/public/images/study/arrow-down-sort.svg
  client/src/assets/study/empty-heart.svg
  client/src/components/study/Study.tsx
  client/src/styles/Study.module.scss
Labels: ✨ Feat

#35 chore: GET /teams API 수정
  server/src/services/team/index.js
Labels: 🐱 chore

#36 chore: GET /teams API 수정
  server/src/services/index.js
  server/src/services/team/index.js
Labels: 🐱 chore

#37 chore: GET /teams API 수정
  server/src/services/index.js
  server/src/services/team/index.js
Labels: 🐱 chore
