Repository ProjectToStudy/sessac-e, pull requests merged in 2023-05, with the labels that each got.

#38 Front end
  client/src/api/study.ts
  client/src/components/study/Study.tsx
  client/src/containers/study/Study.tsx
  client/src/styles/Home.module.scss
Labels: 🛠 Fix

#41 Front end
  client/.eslintrc.json
  client/public/images/home/notification.svg
  client/public/images/home/search.svg
  client/public/images/study/empty-heart.svg
  client/public/images/study/heart.svg
  client/src/App.css
  client/src/api/study.ts
  client/src/components/home/Home.tsx
  client/src/components/home/components/Banner.tsx
  client/src/components/study/Study.tsx
  client/src/styles/Component.module.scss
  client/src/styles/Home.module.scss
  client/src/styles/Study.module.scss
Labels: 🛠 Fix, ✨ Feat, 🐱 chore

#42 Backend
  server/package.json
  server/src/api/routes/team.js
  server/src/api/routes/user.js
  server/src/config/index.js
  server/src/controllers/team.js
  server/src/middleware/validation.js
  server/src/models/categoryInfo.js
  server/src/models/teamAdditionalInfo.js
  server/src/models/teamAreaInfo.js
  server/src/models/teamCategoryInfo.js
  server/src/models/teamInfo.js
  server/src/models/teamPhotoInfo.js
  server/src/models/teamStatsInfo.js
  server/src/models/teamStatusInfo.js
  server/src/models/teamUserInfo.js
  server/src/models/userAdditionalInfo.js
  server/src/models/userCertificationHistory.js
  server/src/models/userLoginHistory.js
  server/src/models/userRequiredInfo.js
  server/src/services/index.js
  server/src/services/team/index.js
  server/src/services/user/index.js
  server/src/utils/sendNotification.js
Labels: 🛠 Fix, ✨ Feat, 🐱 chore

#43 Backend
  server/src/services/index.js
  server/src/services/team/index.js
Labels: 🛠 Fix

#45 Backend
  server/src/services/team/index.js
Labels: 🛠 Fix

#44 Front end
  client/.eslintrc.json
  client/src/App.tsx
  client/src/api/study.ts
  client/src/api/user.ts
  client/src/components/atoms/LikeBtn.tsx
  client/src/components/home/Home.tsx
  client/src/components/study/Study.tsx
  client/src/containers/Home.tsx
  client/src/containers/study/Study.tsx
  client/src/containers/user/Join.tsx
  client/src/containers/user/JoinPlanting.tsx
  client/src/index.css
  client/src/modules/index.ts
  client/src/modules/userInfo.ts
  client/src/pages/Home.tsx
  client/src/pages/Search.tsx
  client/src/pages/index.ts
  client/src/styles/Component.module.scss
  client/src/styles/Home.module.scss
  client/src/styles/Study.module.scss
  client/src/styles/study/Create.module.scss
Labels: ✨ Feat, 🐱 chore
